### ISSUE TITLE
Adguard website cannot detect using Adguard DNS

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardDNS#153]
This used to work previously, but something has happened and now the Adguard website isn’t able to detect that I’m using Adguard DNS, even though it’s definitely setup and active.
<img width="446" alt="screen shot 2017-06-14 at 8 31 02 pm" src="https://user-images.githubusercontent.com/29296810/27128082-9c57b7e8-5140-11e7-9f7b-528aee06be01.png">

Extended DNS leak test results:
<img width="951" alt="screen shot 2017-06-14 at 8 33 48 pm" src="https://user-images.githubusercontent.com/29296810/27128179-e45b7804-5140-11e7-8bb8-610fc765ec11.png">
<img width="947" alt="screen shot 2017-06-14 at 8 34 20 pm" src="https://user-images.githubusercontent.com/29296810/27128182-e56112ea-5140-11e7-8d70-e026fec4ba9b.png">

Also, wasn’t sure if I should’ve said this on a similar closed ticket (#122) or create this as a new issue.

**Comment by vozersky** [comment]
@planet0 hi! could you please run traceroute 176.103.130.130?

**Comment by planet0** [comment]
@vozersky Sure, the output is below.

```
 1  192.168.0.1 (192.168.0.1)  99.719 ms  1.177 ms  1.993 ms
 2  * * *
 3  144.130.211.210 (144.130.211.210)  20.946 ms  19.887 ms  22.498 ms
 4  bundle-ether12.win-core10.melbourne.telstra.net (203.50.11.111)  21.707 ms  21.564 ms  19.797 ms
 5  bundle-ether1.win-edge901.melbourne.telstra.net (203.50.11.106)  20.379 ms  20.534 ms  19.857 ms
 6  aap1604794.lnk.telstra.net (165.228.52.2)  19.529 ms  19.997 ms  20.093 ms
 7  po9.mburndist02.aapt.net.au (202.10.14.36)  29.823 ms  32.103 ms
    po8.mburndist01.aapt.net.au (202.10.14.34)  32.411 ms
 8  te2-1-110.mburndist01.aapt.net.au (202.10.12.138)  32.368 ms
    te0-3-4-0.mburncore01.aapt.net.au (202.10.12.15)  32.584 ms  32.861 ms
 9  te0-3-4-0.mburncore01.aapt.net.au (202.10.12.15)  32.041 ms
    bu2.sclarcore01.aapt.net.au (202.10.10.74)  32.869 ms
    te0-3-4-0.mburncore01.aapt.net.au (202.10.12.15)  34.083 ms
10  bu2.sclarcore01.aapt.net.au (202.10.10.74)  32.342 ms
    po11.sclardist01.aapt.net.au (202.10.12.2)  32.249 ms  32.077 ms
11  po11.sclardist01.aapt.net.au (202.10.12.2)  31.733 ms  31.796 ms
    1-1-1.sclarinte01.aapt.net.au (203.131.60.31)  44.648 ms
12  1-1-1.sclarinte01.aapt.net.au (203.131.60.31)  52.166 ms
    aapt.sy4.nsw.coloau.au.net.au (210.9.30.254)  32.067 ms  31.978 ms
13  aapt.sy4.nsw.coloau.au.net.au (210.9.30.254)  31.545 ms
    dom.as20473-xe-0-3-0.cr2.s1.nsw.au.coloau.net.au (103.52.116.168)  32.522 ms  32.061 ms
14  dom.as20473-xe-0-3-0.cr2.s1.nsw.au.coloau.net.au (103.52.116.168)  32.677 ms
    dom.as20473.cr2.s1.nsw.au.coloau.net.au (103.52.116.169)  33.365 ms
    dom.as20473-xe-0-3-0.cr2.s1.nsw.au.coloau.net.au (103.52.116.168)  31.708 ms
15  dom.as20473.cr2.s1.nsw.au.coloau.net.au (103.52.116.169)  33.173 ms
    vl800-ds1-b5-r1121.aus1.choopa.net (103.43.73.130)  136.888 ms
    dom.as20473.cr2.s1.nsw.au.coloau.net.au (103.52.116.169)  32.583 ms
16  vl800-ds1-b5-r1121.aus1.choopa.net (103.43.73.130)  33.495 ms  32.711 ms *
17  * 176-103-130-130.flops.ru (176.103.130.130)  34.966 ms  33.935 ms
```

**Comment by vozersky** [comment]
@planet0 does https://adguard.com/ru/adguard-dns/overview.html detects you if you open the page in incognito mode?

**Comment by planet0** [comment]
@vozersky No, I haven’t been able to get it working. I’ve also tried in on iOS (with Adguard Pro VPN on and off) and also Chrome on Windows and all have the same result.

<img width="310" alt="screen shot 2017-06-15 at 9 56 43 am" src="https://user-images.githubusercontent.com/29296810/27159593-7a2521a8-51b1-11e7-9772-7dccbda9b2e3.png">

![fullsizerender](https://user-images.githubusercontent.com/29296810/27159594-7b15f63c-51b1-11e7-9e2a-4518985dc0cc.jpg)

**Comment by ameshkov** [comment]
I guess there's a mistake in Sydney's server configuration.

**Comment by xdel** [comment]
@planet0 yes, there was a mistype in our latest version of deployment suite, resulting in an effectively non-working dnscheck-default.adguard.com zone. Only Sydney servers has been deployed with a malfunctioning path, so we has not spotted this before because of very narrow subset of users who was possibly affected.

**Comment by planet0** [comment]
Thanks everyone, I'm unsure if this means that the issue will be fixed at some point?

**Comment by vozersky** [comment]
@planet0 it has been already fixed, should work correctly now, please try it when you'll have a chance

**Comment by planet0** [comment]
All good now! Thank you @vozersky, @ameshkov, @nkartyshov and @xdel!

<img width="310" src="https://user-images.githubusercontent.com/29296810/27181805-821474d4-521c-11e7-93be-b7ede6e6153c.PNG">
<img width="310" src="https://user-images.githubusercontent.com/29296810/27181813-8aae2626-521c-11e7-85be-05e29e23440b.PNG">

**Comment by vozersky** [comment]
@planet0  thank you for reporting this problem!

**Comment by planet0** [comment]
Bad news -- seems like the same issue is occurring again.

**Comment by retrobenny** [comment]
Saw that there was a preset issue message so I looked for a matching issue to mine.
Also,sorry for how long this is,had a lot to say,don't worry its positive.

I can't get it to confirm that I am using Adguard's Default DNS on my laptop through Chrome.
I have the AdBlock Plus extension and its fully armed to the teeth because a site pissed me off with its shifty tactics.
The DNS works fine for browsing,but the site fails to detect that its in use.

![image](https://user-images.githubusercontent.com/16418716/34311701-a30ff8c8-e724-11e7-907e-57a7a587a745.png)

I live in the US and my ISP is Charter Spectrum (Charter branch).
The DNS also fails detection since a much earlier date on my Android SATV Pro (2015) which is why I went for the app. (too bad the required certificate for blocking that exploit https doesn't want to install due to the SATV UI refusing to allow it)
Another thing,I wanted to get the "app" on Windows but unlike the free version on Android which I can openly use with no-catch,it mentions a trial on the download for Windows,so I don't want to touch it because I want everything that the free Android version has like the https ad blocking but for Windows instead,especially since I can't even get my SATV to cooperate with the certificate.

I mainly want additional ad blocking because of the increasing risk of malvertising etc. on https sites that could easily attack my laptop due to it ironically being less protected than my non-rooted Android device aside from the option to disable javascript per-page (an extra measure to avoid shifty ads/anti-adblock so that they can give you shifty ads once you disable ad blocking) which browsers on Android seem to lack.

Besides,Adguard is better than standard ad blocking because it removes the sections from pages before they are even loaded which makes things even safer and speedier! Thanks for that!

I plan to put money online at my own risk to attempt to buy the Windows version of Adguard if its not an irritating subscription-based payment so I can make use of the https ad blocking part and have access to the extra perks.
I swear I can't find search results for "https ad blocking" at all,_not even Adguard shows up_,so Adguard is my only option that I know has support for blocking ads on https.

**Comment by ameshkov** [comment]
> I can't get it to confirm that I am using Adguard's Default DNS on my laptop through Chrome.

I suppose #195 should resolve that issue

**Comment by ameshkov** [comment]
@retrobenny there is a trial period so plz check that it's what you are looking for before.

> if its not an irritating subscription-based payment

There's an option to purchase a lifetime license.

**Comment by retrobenny** [comment]
Thanks.
Tried deleting cache then the site cookies manually but still not showing as enabled upon revisiting the site.
Wondering if its underhanded ISP nonsense causing it to not work.
Likely the accursed repeal could be part of this issue with VPNs being the primary target too.
Doesn't make any sense why it won't show up as working.

**Comment by ameshkov** [comment]
This is simple, it tries to resolve these two domains:
`dnscheck-default.adguard.com`
`dnscheck-parental.adguard.com`

> Wondering if its underhanded ISP nonsense causing it to not work.

It might be if your ISP does DNS hijacking and resolves the test requests by itself.

**Comment by retrobenny** [comment]
Does Adguard on Windows also use the Local VPN method?
There is no FAQ in the KB section on Windows and it doesn't openly mention the Local VPN method there.
Guess I have no choice and I am willing to pay for it whenever I am able to so I don't have to deal with the trial crud.

Can you or any Adguard personnel recommend the best option of online payment service to use so I can make sure to stay the most safe from cyber-crooks due to a service being compromised?
I  was in the middle of Googling Paypal and before I typed further I learned about it being breached,should I just buy a standard highly supported gift card and just use that online directly instead?
This gift card thought was my initial idea accompanying a service because a credit card would be fully retarded to use along with one's own bank account while a gift card has no account trace and can be bought with cash)
In this case,what brands of gift card does Adguard support the most?
(main reason to but it now is to help against the repeal if it helps at all and because DNS is being dumb)

I also checked a false site ping and it proved by a no host error message that it wasn't being hijacked by a rogue attacker server,but that doesn't answer the question of my ISP hijacking it.

**Comment by ameshkov** [comment]
> Does Adguard on Windows also use the Local VPN method?

No, there's a more suitable solution on Windows -- network drivers.

> Can you or any Adguard personnel recommend the best option of online payment service to use so I can make sure to stay the most safe from cyber-crooks due to a service being compromised?

I'd say it would be a virtual credit card with a small balance (if your bank provides such an option).

> I also checked a false site ping and it proved by a no host error message that it wasn't being hijacked by a rogue attacker server,but that doesn't answer the question of my ISP hijacking it.

Try executing this command in the command line and copy/paste the result here:
`nslookup dnscheck-default.adguard.com 176.103.130.130`

If this domain is not resolved, most likely your ISP hijacks the DNS traffic.
If this is the case, I recommend you to look at DNSCrypt (dnsrypt.org).

**Comment by retrobenny** [comment]
I would prefer to use a gift card bought with cash for maximum safety with zero association of personal accounts,they make them with popular credit brands.
I don't care that somewhere says its safer for credit cards because online shopping scam liability of the account owner is 0$ compared to offline being 50$ on average,they can still get tons of information from credit card stuff and find a workaround into stealing much more.
Plus,negotiating with a bank (and waiting at one before then) is more trouble than just losing a buck or two just buying an online-spendable gift card,especially if I can take advantage of a reload-able one if I wanted to.

One issue for Windows 10 though is that VPN is trashed since Creators Update (scoundrels,the one thing they HAD to break on top of Steam game icon links),but does the Adguard driver play nice with Fall Creators Update?

**command results**;

Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>nslookup dnscheck-default.adguard.com 176.103.130.130
Server:  176-103-130-130.flops.ru
Address:  176.103.130.130

Name:    dnscheck-default.adguard.com
Addresses:  2a00:5a60::ad1:fa
          91.239.26.15

**Comment by ameshkov** [comment]
> Plus,negotiating with a bank (and waiting at one before then) is more trouble than just losing a buck or two just buying an online-spendable gift card,especially if I can take advantage of a reload-able one if I wanted to.

I guess it depends on the bank. For instance, my bank provides an option to create a virtual card in a couple of clicks, that's why I suggested it.

> Edit: Take note I am from the US in case there is an issue with the results all listing the server from Russia instead of the .en version.

To check what exact server is used execute `traceroute 176.103.130.130` and check the last hops addresses (or copy/paste the output here, I'll tell you which one is in use).

You're seeing `*.flops.ru` not due to the server location, but because this is the hosting provider that owns the IP address (we have a long-term contract with them so that only we could use that IP range).

> One issue for Windows 10 though is that VPN is trashed since Creators Update (scoundrels,the one thing they HAD to break on top of Steam game icon links),but does the Adguard driver play nice with Fall Creators Update?

Generally, yes, there are no issues. But on Windows with all the different AVs and other network-related software one can install, you can't be sure, and that's why the trial period is important.

> Edit 2: Does it make any difference I am using an old-gen wifi adapter in place of my garbage qualcomm wifi chip on my laptop?

It shouldn't.

> command results;

Huh, so it works! I wonder why not in Chrome.

**Comment by retrobenny** [comment]
Command was wrong for me,it was "tracert" instead of route.

There is a LOT of Charter hops in here but I am most additionally concerned about the transtelecom ones.
Also the mastertelecom one as well. At least flops is on there.

  1     1 ms    <1 ms    <1 ms  Linksys04266 [192.168.1.1]
  2     *        *        *     Request timed out.
  3    11 ms    11 ms    10 ms  96-34-75-245.static.unas.sc.charter.com [96.34.75.245]
  4    11 ms    10 ms    11 ms  dtr06ledsal-bue-230.leds.al.charter.com [96.34.79.166]
  5    19 ms    19 ms    18 ms  crr01sghlga-bue-200.sghl.ga.charter.com [96.34.78.18]
  6    21 ms    31 ms    23 ms  bbr01atlnga-bue-3.atln.ga.charter.com [96.34.2.70]
  7    27 ms    30 ms    23 ms  bbr02atlnga-bue-7.atln.ga.charter.com [96.34.0.25]
  8    30 ms    30 ms    30 ms  bbr01atlnga-tge-0-1-0-8.atln.ga.charter.com [96.34.0.132]
  9    28 ms    30 ms    31 ms  bbr01gnvlsc-bue-800.gnvl.sc.charter.com [96.34.0.134]
 10    40 ms    38 ms    38 ms  bbr01aldlmi-tge-0-0-0-13.aldl.mi.charter.com [96.34.0.161]
 11    44 ms    44 ms    44 ms  prr01ashbva-bue-3.ashb.va.charter.com [96.34.3.51]
 12    37 ms    36 ms    44 ms  ahn.eqx.transtelecom.net [206.126.236.233]
 13   180 ms   172 ms   165 ms  mskn08.mskn192.transtelecom.net [188.43.11.190]
 14   173 ms   170 ms   171 ms  mastertel-gw.transtelecom.net [188.43.11.189]
 15   179 ms   178 ms   179 ms  217-67-176-54.in-addr.mastertelecom.ru [217.67.176.54]
 16     *        *        *     Request timed out.
 17   185 ms   177 ms   175 ms  176-103-130-130.flops.ru [176.103.130.130]

**Comment by ameshkov** [comment]
Yeah, you're being routed to the RU server for some reason. That route is shorter for your ISP, that's why it happens.

Unfortunately, misrouting happens, and the only solution for that is to provide more servers in different data centers worldwide. Eventually, we'll do that.

**Comment by retrobenny** [comment]
Ah,that's a relief I guess though it sucks for anyone else that also can't avoid the issue of it getting misrouted.
Guess since that is why my Android device also failed with just the DNS,maybe I will go for another DNS server for now that works more closely to my area.

Also,with that certain CPU issue since June,I really need all of the extra buffs of protection I can get.
Even with the patch (band-aid) it can still be exploited by the hackers learning how the exploits work.
