### ISSUE TITLE
Problem with DNSCrypt protocol

### ISSUE THREAD

**Issue by gimenes2008** [AdguardTeam/AdGuardDNS#165]
Hi,

I am an Android 8.1.0 and AG 3.6.2 user. I use the 'Local VPN' filtering method and I've set my phone to block connections until AdGuard protection is active.

Well, in AG's 'DNS Filtering' settings I choose AG's DNS server and I've always chosen the DNSCrypt protocol, but this protocol has been showing connection breaks that force me to change to another one (DoT, DoH, for example, work without problems). When trying to access any website through Chrome returns the message saying that it could not find the DNS address.

It's important to say that any other internet access application likes Gmail, for example, finds connection difficulties when DNSCrypt protocol is enabled.

**Comment by Chinaski1** [comment]
Hello there!

I checked your request and did not encounter a specified issue when using DNSCrypt.
Looks like the problems with the blocked connection is a local one. 
It is difficult to say what causes this behaviour, it may be due to a combination of settings, or the ISP is blocking the port that DNSCrypt uses.
Probably the best solution is to use a DNS server with a different protocol.
