### ISSUE TITLE
OpenSource

### ISSUE THREAD

**Issue by LegitSoulja** [AdguardTeam/AdguardDNS#194]
Hey. I was wondering when in the near future of the possibilities of an open source release? 

I'm interested in how it works mostly, and for the use with my company. I was looking for something like this to handle traffic a certain way but was never able to pull it off.

Any beta releases, or more in dept resources of how AdGuard work would be nice :)

**Comment by ameshkov** [comment]
The plan is to publish the source code once it is out of the beta testing stage. The problem is that while doing the beta test we decided to throw away everything and rewrite it, and that's why it takes so long :(

Current architecture is: `frontend BIND <-> AG DNS server (written in java at the moment) <-> backend BIND --> upstream DNS servers`. AG DNS server is basically a UDP proxy that's able to parse incoming DNS requests and decide whether or not the request should be blocked or modified. It understands ad blocking rules syntax (instead of heavy hosts files).

The problem with the current implementation is that you can't simply set it up on a low-end device (router for instance) as all three parts of it are quite heavy. That's why we're rewriting it.
