### ISSUE TITLE
System DNS Override on iOS on T-Mobile USA

### ISSUE THREAD

**Issue by jravid** [AdguardTeam/AdguardDNS#202]
### Steps to reproduce

1. Download Adguard Pro on iOS 11 on iPhone X running on T-Mobile USA
2. Add AdGuard DNS servers in IPv6 form as custom DNS server in app
3. Make sure that you are using the T-Mobile USA cellular network, and are not on Wi-Fi
4. Activate DNS Settings

### Expected behavior
Ads should be blocked

### Actual behavior
Ads are not blocked, and an error is thrown in the app. It reads: "**Warning** You are connected to an ipv6-only network. In such networks you cannot use custom DNS servers. The 'System Default' DNS settings will be used instead."  
  
It seems that using an IPv6 DNS server address alone isn't enough to get around the T-Mobile IPv6-only issue. I saw this mentioned briefly on the AdGuard Reddit ([here](https://www.reddit.com/r/Adguard/comments/6wejit/is_it_no_longer_possible_to_do_systemwide/)), but didn't see a resolution and/or an official issue opened on GitHub, so hopefully you have some idea of the steps that would need to be taken to fix this. Please let me know if I can help at all!

<details><summary>Screenshots:</summary>

![img_2122](https://user-images.githubusercontent.com/18693464/32429360-4cd61d6c-c298-11e7-84c6-2867718e3aff.PNG)
![img_2123](https://user-images.githubusercontent.com/18693464/32429361-4cdef158-c298-11e7-8a93-e3aab2116ad4.PNG)
![img_2124](https://user-images.githubusercontent.com/18693464/32429362-4ce8070c-c298-11e7-935c-32c27f1f67ca.PNG)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS servers in use:| 2a00:5a60::ad1:0ff, 2a00:5a60::ad2:0ff |
| How did you set up DNS configuration:| In app |
| Device model:| iPhone X |
| Network:| T-Mobile USA |
| Operating system and version:| iOS 11.1 |

**Comment by LaxusiC** [comment]
i don't think current ios pro version support ipv6, you can try ipv4

**Comment by Bluscream** [comment]
crapple :thinking:

**Comment by ameshkov** [comment]
Hm, @jravid could you please try using a custom DNS port?

Something like that:
`[2a00:5a60::ad1:0ff]:5353`

@nkartyshov do we support port 5353 for IPv6?

**Comment by ameshkov** [comment]
@jravid  could you please reproduce the issue and export AG logs?

Here's how:
https://kb.adguard.com/en/ios/solving-problems/dns-requests-log

Instead of sending a message to the support service, you can grab the logs and attach to this issue.

**Comment by jravid** [comment]
@ameshkov Sure thing, will try all the above and update accordingly, just need a day. Thanks everyone!

**Comment by jravid** [comment]
@ameshkov 
1. I tried using a custom DNS port in the format described, but still no luck. Ads still come through.
2. A good temporary solution has been adding to the blacklist the simplified list that you posted on the Reddit thread which I mentioned in the initial issue post, but I've made sure to have nothing blacklisted for the purposes of testing, such that we can get a completely accurate picture of what's going on.
3. I followed the instructions provided for exporting logs, and I'm attaching the relevant files to this comment. Please let me know if there's anything I'm missing, or if there's any other way that I can help!

[filter.gz](https://github.com/AdguardTeam/AdguardDNS/files/1449336/filter.gz)
[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardDNS/files/1449337/com.adguard.AdguardPro.gz)
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardDNS/files/1449338/com.adguard.AdguardPro.tunnel.gz)
[state.txt](https://github.com/AdguardTeam/AdguardDNS/files/1449339/state.txt)

**Comment by jravid** [comment]
Do we have a better picture as to what's happening yet?

**Comment by ameshkov** [comment]
@jravid hi! Sorry for the late reply, got my hands full this week. I'll look into it later.

> A good temporary solution has been adding to the blacklist the simplified list

Yeah, the thing is that blacklist works locally, thus it cannot be hijacked by T-Mobile like it happens with regular DNS traffic.

**Comment by jravid** [comment]
@ameshkov Thanks the update! Out of curiosity, given that the workaround of adding entries to the blacklist (but still using the system DNS settings) seems to work well, wouldn't it be easy to simply add a feature wherein instead of manually typing in or copy-pasting blacklist entries, one can input a URL, and the app woul then automatically pull from and update the blacklist according to the context of the URL? (The URL would be in a format similar to [this](https://filters.adtidy.org/windows/filters/15.txt) I imagine).

**Comment by lancelot-moon** [comment]
@jravid 
@ameshkov 
@IvanIin

Hi jravid,
I also met the similar issue, but it occurred when my iPhone surfed on internet over my Android phone hotspot Wi-Fi.
https://github.com/AdguardTeam/AdguardForiOS/issues/528

AdGuard's developer said it's because of DNS hijacking.
Yesterday, I came back to my home town from another county.
I tried to again let my iPhone surf on internet over my Android phone hotspot Wi-Fi.
The same ISP...
However, the filter of AdGuard DNS server became to work.
Is there a difference between the same ISP's cellular network hosts in different counties?

But I still doubt that it's AdGuard Pro's bug.
Can you try DNS Override?
https://itunes.apple.com/us/app/dns-override-set-dns-for-wi-fi-and-cellular/id1060830093?mt=8
But DNS Override feature needs $1.99.

Or do you have another T-Mobile USA cellular network's sim card for Android phone?
Please try DNS Changer (No Root - IPv6 - All connections).
https://play.google.com/store/apps/details?id=com.frostnerd.dnschanger&hl=zh_TW

You set AdGuard DNS server in DNS Changer (No Root - IPv6 - All connections).
AdGuard DNS server:
IPv4 addresse
176.103.130.130
176.103.130.131

IPv6 addresses
2a00:5a60::ad1:0ff
2a00:5a60::ad2:0ff

View if ads can be blocked by AdGuard DNS server and then report here.
If ads can be blocked by AdGuard DNS server over T-Mobile USA cellular network when using DNS Override on iPhone or DNS Changer (No Root - IPv6 - All connections) on Android phone, we can sure that it's AdGuard Pro's bug.

Thank you very much sincerely!

**Comment by ameshkov** [comment]
> wouldn't it be easy to simply add a feature wherein instead of manually typing in or copy-pasting blacklist entries, one can input a URL, and the app would then automatically pull from and update the blacklist according to the contents of the URL?

Absolutely, we should provide an "import" feature.

**Comment by ameshkov** [comment]
I have an idea about how to fix the issue with T-Mobile, but we need help from users. Details are here:
https://github.com/AdguardTeam/AdguardForiOS/issues/796
