### ISSUE TITLE
Blocking From External Lists Not Working

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardDNS#217]
AD Pro 4.3.2 (938) and iOS 15.3

I found out that the blocking isn't working properly with external DNS list. 

For instance the request:
https://app-measurement.com/sdk-exp
goes through although it is present into my DNS list.
https://badmojr.github.io/1Hosts/Pro/domains.txt
![image](https://user-images.githubusercontent.com/49731083/152798269-3bc2ed04-5c4c-45ae-9de4-f5cc5a651aa3.png)

Not mentioning that the updates of  external DNS lists don't seem to work either. 

Does AG changed the rules to use other DNS lists than their own?

**Comment by ameshkov** [comment]
Note that this `https://app-measurement.com/sdk-exp` is not a valid DNS query.

The thing is that somewhere in Google libraries there's an old bug that triggers a DNS query with an invalid domain name (URL is obviously not a domain). That's why it is not covered by regular blocking rules since they're supposed to match domain names.

You can prevent this particular DNS query by using a regular expression rule: `/app-measurement.com/`, but tbh it does not make much sense, this query cannot be resolved anyways and there's no data leak since the recursive resolver won't even try to resolve this.

**Comment by Quorum75** [comment]
Thanks for the response.

I didn't understand why you were mentioning Google libraries but after reading this thread 

https://discourse.pi-hole.net/t/can-t-add-https-app-measurement-com-sdk-exp-to-blocking-list/39971

I found out that the only Google app I have, Translate, might be responsible for it. 
My paranoïa still pushed me to add it manually to my personal blocking list. 

Cheers
