### ISSUE TITLE
AdGuard DNS Beta - Statistics empty

### ISSUE THREAD

**Issue by TheCeet** [AdguardTeam/AdGuardDNS#232]
Since yesterday at noon AdGuard DNS Beta doesn’t log any statistics. 
I can still see the last activity, that is up-to-date. But there ar 0 queries and all other info logged. 
on Reddit, many others experiencing same issue. 
https://www.reddit.com/r/Adguard/comments/tztk4l/adguard_dns_beta_currently_broken

**Comment by ameshkov** [comment]
We're looking into it, thank you for reporting the issue!

**Comment by ameshkov** [comment]
The issue is resolved.

**Short technical post-mortem**

AdGuard private DNS customers' logs are loaded into a Clickhouse database through a [clickhouse bulk](https://github.com/nikepan/clickhouse-bulk) instance. At some point the proxy decided that the clickhous instances are dead and stopped loading new logs there. We're yet to figure out why it thought so. The main issue was that we didn't detect this situation at the right moment and the beta testers noticed that there's no data in the statistics and in the logs.

What we're going to do now:
1. First of all, set up the proper monitoring so that we could learn about such issues right when they happen and not on the next day.
2. We're going to investigate further to figure out what caused the original issue in the first place.
