### ISSUE TITLE
Singapore server not responding to DNS queries (host is up)

### ISSUE THREAD

**Issue by ForkedLightning** [AdguardTeam/AdguardDNS#274]
Since a few hours ago, the Singapore server (all addresses including family protection) stopped responding to DNS queries but it can be pinged. Other regions is assumed to be OK - tested EU and it was working.

**Comment by ForkedLightning** [comment]
It's working now. Thanks!

**Comment by FengLengshun** [comment]
Okay, what _is_ up with the Singapore DNS server? It just so often down, not responding, or slow. I really want to use AdGuard DNS for my DNS server, especially since it's a simple foolproof solution to make sure my parents didn't get potentially harmful ads or access malware and phishing sites. But it's just very unreliable here, with whatever server Indonesia's using (Singapore, last I heard).
