### ISSUE TITLE
Use Quad9 as Upstream Provider

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardDNS#292]
I'm proposing that you consider using [Quad9](https://www.quad9.net/) as your upstream provider.

According to services like [DNS leak test](https://www.dnsleaktest.com/) and [Tenta](https://tenta.com/test/), AdGuard DNS appears to be using upstream resolvers like Google, Cloudflare, and OpenDNS. There are a large number of security, privacy, and performance benefits of Quad9, as described on [their website](https://www.quad9.net/about/), which would directly benefit all AdGuard DNS users.

Thanks in advance for your consideration!

**Comment by hmage** [comment]
Hello!

Thank you for taking your time to propose new upstream provider. Unfortunately, in case of Quad9, there are several things that don't make it a good fit, at least currently:

 * Security — We have our own solution for blocking malicious domains, and if we start using quad9, it will unfortunately clash with our own and, in case of problems or false positives from our blocks, will make difficult to troubleshoot remotely if it's our block causing this or quad9's, especially since if it's just only one of many upstream providers and clients will get a blocked domain one minute and same domain without block next minute.
 * Performance — on our servers, ping to 9.9.9.9 is much higher than to google or cloudflare (1ms vs 37ms).
 * Privacy — all upstream providers see requests originating from our servers, not our clients. For them it's one big client doing all the requests.

And, again, reasons above do not mean that our current list of upstream providers is set in stone and will never change — if needed, we will adjust accordingly.

It also doesn't mean that we are not open for ideas and proposals, I hope my explanation for this particular upstream provider is sufficient.

I'm closing this ticket, but feel free to reply here if you have further questions or comments.
