### ISSUE TITLE
The source code can not be compiled

### ISSUE THREAD

**Issue by JamesXatu2** [AdguardTeam/AdguardDNS#330]
After installing the following versions of [go ](https://dl.google.com/go/go1.11.linux-amd64.tar.gz)and [node.js](https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-armv7l.tar.xz) I downloaded your source code and I do the make

![screenshot_1](https://user-images.githubusercontent.com/43168947/45350566-5df6db80-b5b4-11e8-990f-477149023150.jpg)

I use Ubuntu 16.04.5 LTS with 4.4.70-BPI-R2-Kernel for more [information](https://bananapi.gitbooks.io/banana-pi-bpi-r2-open-source-smart-router/content/)

**Comment by hmage** [comment]
Hi!

It looks like you've downloaded wrong version of go.

Please verify this by running `go version`. It should fail with same error (unterminated quoted string).

If that is the case, you need to download go for ARMv6, it's on https://golang.org/dl/ if you scroll down a little bit.

And thanks for the link — otherwise it wouldn't have been easy to figure out that the problem was because of wrong architecture.

If the problem still persists or you have any further questions, please let me know and feel free to reopen this issue.

**Comment by JamesXatu2** [comment]
Thank you very much for the suggestion, I downloaded the [version](https://dl.google.com/go/go1.11.linux-armv6l.tar.gz) you suggested, but this is what presents itself to me.
![screenshot_20180911-140503](https://user-images.githubusercontent.com/43168947/45359106-d1f0ae00-b5cb-11e8-968f-3f655bfd240b.png)
![screenshot_20180911-140516](https://user-images.githubusercontent.com/43168947/45359121-d87f2580-b5cb-11e8-803b-c1385bb34fa0.png)
![screenshot_20180911-140523](https://user-images.githubusercontent.com/43168947/45359132-de750680-b5cb-11e8-9424-5c8dd95042ef.png)

**Comment by hmage** [comment]
You ran out of free space on disk/flash -- it's visible on last picture.

**Comment by JamesXatu2** [comment]
Thanks a lot! Now compile!

**Comment by hmage** [comment]
You're welcome! 🎉
