### ISSUE TITLE
Doh in Firefox not working. 

### ISSUE THREAD

**Issue by Techguyprivate** [AdguardTeam/AdGuardDNS#4]
![screenshot from 2018-12-30 13-27-56](https://user-images.githubusercontent.com/43615747/50545353-c1ab2000-0c08-11e9-8d4e-bf44987b980e.png)
 Anything else  I need to change . Linux mint 19.1 . I have installed certificate in firefox too.

**Comment by Techguyprivate** [comment]
Letting the network.trr.custom_url blank with changing the network.trr.uri to https://dns.adguard.com/dns-query , doesn't work too.

**Comment by mpas97** [comment]
@Techguyprivate I have set uri and mode to 2 only. Everything works as expected. As soon as mode is set to 3 it doesn't work anymore.

The check on their website is successful:
<img width="404" alt="grafik" src="https://user-images.githubusercontent.com/9994218/50592513-b8ce7e80-0e94-11e9-816b-e221b184bdbc.png">

**Comment by Techguyprivate** [comment]
But why is that ? Setting uri 3 ensures only adguard doh works, not other insecure default operating system or ISP'  DNS. Cloudflare works properly with uri 3.

**Comment by mpas97** [comment]
I asked me the same question. Now I did some debugging (using about:networking#dns) to find the reason. I think it's because we need a DNS to resolve dns.adguard.com first, but we block that step with mode == 3. As soon as we know the DoH-DNS-IP we can continue using TRR.
<img width="931" alt="grafik" src="https://user-images.githubusercontent.com/9994218/50608620-6fe6ec00-0ecd-11e9-95ef-912f039ba3c7.png">

Using an IP instead of a hostname in trr.uri doesn't work either because then we get a tls cert error.

**Comment by mpas97** [comment]
So the solution is to fill the bootstrapAddress field too:
<img width="1091" alt="grafik" src="https://user-images.githubusercontent.com/9994218/50610515-84c67e00-0ed3-11e9-81dd-974d73b38032.png">

**Comment by AMihail1** [comment]
Getting the same issue - TRR forced on (3) was working for my Cloudflare setup but not with Adguard DoH. We need the correct bootstrap address.
