### ISSUE TITLE
Adguard DNS blocks push notifications in Win10

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#42]
Source:
https://forum.adguard.com/index.php?threads/adguard-dns.13530/#post-100180

**Comment by sandybeachit** [comment]
Out of interest did this issue get resolved or is it outstanding? I can do some testing if it is?

**Comment by vozersky** [comment]
Not sure, actually
I remember running a quick test at the times when it was reported.  I was not able to reproduce it.
I would really appreciate if you could also give it a try.
You can use https://dnscrypt.org/#dnscrypt-windows if you want.

**Comment by sandybeachit** [comment]
Ok so for the test is it just adguard DNS I should use or adguard DNS with dnscrypt?

I have adguard DNS running all the time on android, I'm using a DNS changing app to force using the adguard DNS even after a reboot and I do get alerts for email, application updates, WhatsApp message updates.

At home I run Windows 10 pro with all updates and malwarebytes pro just for the record, I don't remember missing any notifications but I'll give it another try with a bunch of windows 10 metro apps and web based chrome apps like Zoho mail and let you know what I find.

**Comment by vozersky** [comment]
I think it's up to you. But it was reported without DNSCrypt.

**Comment by sandybeachit** [comment]
From what the user says in your forum on the above URL about redirections I don't think that's a problem anymore, I use PayPal all the time with eBay and Amazon.

I do see some issues with redirections which I report in the forum's like htrax and Google which is fixed so it might be this he is referring to which was fixed since then as your DNS server is fast for me and I am in London, the only time it goes slow is when a site fails to load like having an adblocker warning or a redirect break.

I'll do some testing and let you know what I find :)

**Comment by sandybeachit** [comment]
Cool ok I'll do it without dnscrypt so I'm as near as the user settings wise

**Comment by vozersky** [comment]
Can't reproduce, looks like it's resolved now.
@sandybeachit please let me know if something goes wrong with those notifications at your end
