### ISSUE TITLE
Routing issues on AS139762

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#423]
> I'm reaching out to you regarding the routing optimization issue. The current routing for 94.140.14.14 from AS139762 is not optimized. The latency should be around 50 ms. Unfortunately,  the upload path is through Singapore via equinIX, download path is via AS10075 which is via Mumbai IX. Due to asymmetric routing we are getting higher average latency. We have an automated download path via BGP. 

Please find traceroute in the 642114 support ticket.

**Comment by D13410N3** [comment]
At first, we can't affect on path "AdGuard DNS -> your device" in this case

Based on provided traceroute-results, your route to AdGuard DNS is correct - Singapore is the shortest path for you. At this moment we have no servers closer to you (but we're working on this).

Your average latency is about 60 ms, but your packets are going through your provider network for about 40 ms, so, you should try to contact him to decrease latency.


Sorry, but we can't help you in this case

**Comment by SagorThePerfection** [comment]
I'm aware of the fact that SG is the shortest path for me. Unfortunately, I'm getting the download path of your DNS via Mumbai resulting higher avg. Latency.

If you observe carefully, you would notice that my upload path is via Singapore whereas my download path is via Mumbai IX. Due to this assymetric path issue you are seeing the descripancies.

As you know my download path is , your upload path. And you should also be aware of that changing upload path is less complicated than changing download path.  I'm just requesting you to route your DNS server's upload path via SG rather than Mumbai IX for AS58656(My upstream) or for AS139762(My ISP).
