### ISSUE TITLE
Parental Services blocked Netflix from logging in

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#496]
With Netflix blocking turned off in Parental Services, but Amazon blocking turned on, AdGuard DNS prevents logging into Netflix on Android.

I would assume if Netflix blocking was turned off, I would be able to login to Netflix regardless of any other blocked service status.

<img width="255" alt="Screenshot 2023-01-07 at 3 17 26 pm" src="https://user-images.githubusercontent.com/95468948/211132492-ff347770-2055-4799-9645-85081b396f29.png">

**Comment by hagezi** [comment]
When Amazon is activated, AWS is completely blocked and so is half the internet. Since Netflix uses AWS, it is not accessible.

https://github.com/AdguardTeam/HostlistsRegistry/blob/c08eef894653b0bb24821ee7d9b746c5900a25c6/assets/services.json#L71

This should be changed.

**Comment by ameshkov** [comment]
It's blocked because `android-appboot.netflix.com` is a CNAME to several AWS domains.

Possible solutions:

1. Do not apply services rules to CNAMEs.
2. Refactor the services list and move AWS to a separate category.
3. Just don't block CNAMEs of `amazonaws.com`, we can use this rule instead: `||amazonaws.com^$dnstype=~CNAME`

What do you think?

**Comment by hagezi** [comment]
I don't know if there are other side effects from the rules added last. Since only the problems with AWS exist at the moment, I would tend towards 3. for amazonaws.*
