### ISSUE TITLE
please add hagezi blocklists

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#515]
https://github.com/hagezi

**Comment by Alex-302** [comment]
What exactly?

**Comment by ijuliank** [comment]
> What exactly?

![image](https://user-images.githubusercontent.com/64658680/213749008-20524650-72c3-4372-b1d7-2041a0d8207b.png)

**Comment by jslawler** [comment]
A [PR](https://github.com/AdguardTeam/HostlistsRegistry/pull/101) was already closed for these due to potential duplicates/overlapping with other lists.

@hagezi created in its place [this](https://github.com/AdguardTeam/HostlistsRegistry/pull/103) list instead which is already available in AGDNS as _HaGeZi Personal Black & White_.

<img width="496" alt="Screenshot 2023-01-21 at 2 50 23 am" src="https://user-images.githubusercontent.com/95468948/213756372-a559a3be-6248-4992-9f73-20ba66974265.png">

[Homepage](https://github.com/hagezi/dns-blocklists)
[Source](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal-blackwhite.txt)

**Comment by ijuliank** [comment]
> A [PR](https://github.com/AdguardTeam/HostlistsRegistry/pull/101) was already closed for these due to potential duplicates/overlapping with other lists.
> 
> @hagezi created in its place [this](https://github.com/AdguardTeam/HostlistsRegistry/pull/103) list instead which is already available in AGDNS as _HaGeZi Personal Black & White_.
> 
> <img alt="Screenshot 2023-01-21 at 2 50 23 am" width="496" src="https://user-images.githubusercontent.com/95468948/213756372-a559a3be-6248-4992-9f73-20ba66974265.png">
> 
> [Homepage](https://github.com/hagezi/dns-blocklists) [Source](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal-blackwhite.txt)

these black and white are diffrent than in the screen

**Comment by jslawler** [comment]
They are, but they were also rejected to prevent users enabling too many filters have having possible conflictions.
