### ISSUE TITLE
Adguard DNS Status page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardDNS#6]
@TPS commented on [Fri Jun 01 2018](https://github.com/AdguardTeam/AdGuardHome/issues/281)

Every few weeks, AGDNS will go down for me.  I'd love to have dedicated (even automated), authoritative page (on an independent server, naturally) that shows what, if any issues, AGDNS is detected as having.

A great example close-to-home, as-it-were: https://status.github.com/

**Comment by ameshkov** [comment]
It is much more stable now but having a status page still makes sense

**Comment by thomasjcf29** [comment]
@ameshkov, after the recent DNS Node issues where I've had on/off intermittent DNS problems due to the node in Amsterdam, NL being geo-IP blocked.

Are we able to have a look at setting a milestone/deadline for this piece of work?

If I'm having issues at my house/company for a month where we experience on/off intermittent issues I would like to know if the problem is on my end / your end with ease.

I would happily pay for this feature, but it seems essential in this day and age that a company should be able to easily inform their customers if they are experiencing an outage/degraded performance.

**Comment by TPS** [comment]
I'd consider this solved by https://status.adguard.com/, but it'd be nice if it were clearly displayed @ https://adguard.com/adguard-dns/overview.html.
_Note:  Though I'm the OP, since I posted this in the wrong issue tracker 😅 & then @ameshkov moved it here via ZenHub, I can't close this.  Any admin willing?_

**Comment by ameshkov** [comment]
Well, since it's not just AdGuard DNS, I doubt it needs to be on the product page.

But you can find it in the website footer.

**Comment by TPS** [comment]
I _did_ see it there before posting, but it's quite hidden.  I was hoping for a bit more visibility on _each_ of the services' homepages for its own metric as a snapshot of current status, as well — maybe kind-of an automated badge.

**Comment by ameshkov** [comment]
Well, it's just not that important to a regular user and that's why it's not highlighted.
