### ISSUE TITLE
Suggestion: Option to remember login in website

### ISSUE THREAD

**Issue by metronightly** [AdguardTeam/AdGuardDNS#644]
### Issue Details

Currently, after every browser/device restart, I get logged out of my adguard dns account. It's slightly inconvenient to users and an option to remembers logins upon browser restart would be nice.

### Proposed solution

Adding a checkbox to remember login in the login page of adguarddns.

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1603

**Comment by FsAguard62** [comment]
How come, I have to log in to my Adguard account to access the Adguard-dns website all of the time now? I assume, guess it isn’t monitoring my network traffic anymore, If I have to log in to it again and again every time and day when I open any of my browsers, I guess the “your” cookie is expiring really fast these days.

**Comment by Chinaski1** [comment]
We can't increase the cookie lifetime for technical reasons.

But we have [improved the login](https://uploads.adguard.org/Chinaskise606.png) behavior in the [v2.4 update](https://adguard-dns.io/en/versions.html).
Now we remember the last email address, you only have to click Login.

**Comment by FsAguard62** [comment]
Greetings,

Now, I have to log in to my AdGuard account first to access the AdGuard DNS website all of the time, and once the AdGuard account cookie expires the AdGuard DNS website no longer works even if I have it open in the background because it refreshes in the foreground and makes me sign in again this is annoying to me and this goes for all of my browser apps on all of my apple iDevices.

Sincerely,Frank S. 

On Thursday, November 2, 2023, 5:32 AM, Konstantin ***@***.***> wrote:




We can't increase the cookie lifetime for technical reasons.

But we have improved the login behavior in the v2.4 update.
Now we remember the last email address, you only have to click Login.
