### ISSUE TITLE
some users said they reach 10million querys easy only not the time to mail about it

### ISSUE THREAD

**Issue by miixms** [AdguardTeam/AdGuardDNS#692]
### Issue Details

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/149260892/7c645ff4-382c-41e3-817d-7913fd06447e)
he also said he can reach the maximum of it also

### Proposed solution

increase the limit

### Alternative solution

or remove the limit and go unlimited

**Comment by hagezi** [comment]
@Chinaski1 In a nutshell, 10 million requests per month are too few for some networks, hence the request to lift the limit completely or to increase the limit.

**Comment by ameshkov** [comment]
We had this discussion with the topic starter before and we're not seeing any issues on our side, 99.99% of people are not even close to the limit.

There're just a handful of people who can reach it (due to misbehaving IoT devices for instance). In the new version of AG DNS there will be a feature that could help (although, the reason for adding it is different). In the next version we're bringing "Access settings" to AdGuard DNS, pretty much the same thing as we have in AdGuard Home. Users will be able to disallow DNS queries from specific IP addresses, networks, or even specific DNS queries. Disallowed queries will be dropped and won't be counted towards the queries limit.
