### ISSUE TITLE
Incompatibility with systemd-resolved (AdGuard DNS - DoT)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardDNS#73]
### Current Issue
It seems that systemd-resolved only supports verifying TLS certificates where the IP address is specified within the certificate. As we do not have our IP address present in the certificate, Linux's systemd-resolved fails to work with AdGuard DNS (DoT).

### Associated tickets
https://github.com/systemd/systemd/issues/14637 (filed by the customer)

**Comment by ameshkov** [comment]
We're going to resolve this in a couple of weeks.

**Comment by carloabelli** [comment]
Any update on this? (I was the original reporter)

**Comment by ameshkov** [comment]
@carloabelli it takes quite some time.

Briefly, we had to purchase a new range of IP addresses as the long-term rental agreement does not allow purchasing a TLS cert with IP addresses. Now that this new address range is acquired, we'll need some more time to start using it and start to slowly migrate from the old IPs.

**Comment by Mikaela** [comment]
I thought this would be fixed by https://github.com/systemd/systemd/pull/14210, but that doesn't seem to be the case. 

I was trying with `DNS=2a00:5a60::ad2:ff#dns.adguard.com 176.103.130.131#dns.adguard.com 2a00:5a60::ad1:ff#dns.adguard.com 176.103.130.130#dns.adguard.com` on systemd 245.7-1 on Debian Testing/bullseye.

**Comment by carloabelli** [comment]
@Mikaela Thanks for linking the added SNI support. I'm running systemd 245.7 on Arch and managed to get it working with the following line:
```
DNS=176.103.130.130#adguard.com 176.103.130.131#adguard.com 2a00:5a60::ad1:0ff#adguard.com 2a00:5a60::ad2:0ff#adguard.com
```

I also tested
```
DNS=176.103.130.130#dns.adguard.com 176.103.130.131#dns.adguard.com 2a00:5a60::ad1:0ff#dns.adguard.com 2a00:5a60::ad2:0ff#dns.adguard.com
```
which also worked. Not sure why it wouldn't work on Debian Testing.

**Comment by alex19EP** [comment]
hello i am interested: does new ip addresses support this?

**Comment by ameshkov** [comment]
Not yet, but they'll soon

**Comment by ameshkov** [comment]
Finally:

DOH: https://94.140.14.14/dns-query
DOT: tls://94.140.14.14

Works with all new IP addresses

**Comment by carloabelli** [comment]
Thank you for resolving this!

As a side note, since this issue was filed, systemd-resolved supported specifying a custom domain name for certificate validation. I was using `adguard.com` as the domain, which is no longer valid per the certificate (and caused my resolving to break again when this change was made). The setting can now be omitted thanks to the IP addresses being added as SANs or looks like one can use `dns.adguard.com`. Just wanted to post that here in case anyone else encountered this issue, not an issue on the AdGuard side.
